# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LBfkBROiJCg3bB4uHJIRL89DeyW6t0zc
"""

import streamlit as st
import subprocess

# Load the uploaded script file
SCRIPT_PATH = "untitled0.py"

def read_script():
    """Reads the script file and returns its content."""
    try:
        with open(SCRIPT_PATH, "r") as file:
            return file.read()
    except Exception as e:
        return f"Error reading script: {e}"

def run_script():
    """Runs the script and captures the output."""
    try:
        result = subprocess.run(["python", SCRIPT_PATH], capture_output=True, text=True)
        return result.stdout if result.stdout else result.stderr
    except Exception as e:
        return f"Execution error: {e}"

st.title("Python Script Runner")

# Display the script
st.subheader("Script Code")
script_content = read_script()
st.code(script_content, language="python")

# Button to execute the script
if st.button("Run Script"):
    st.subheader("Script Output:")
    output = run_script()
    st.text(output)
